apiVersion: gpu.dra.intel.com/v1alpha
kind: GpuClaimParameters
metadata:
  name: gpu-params2
spec:
  count: 1
  type: "gpu"
  memory: 256
---
apiVersion: resource.k8s.io/v1alpha1
kind: ResourceClaim
metadata:
  name: gpu-claim2
spec:
  resourceClassName: intel-gpu
  allocationMode: Immediate
  parametersRef:
    apiGroup: gpu.dra.intel.com/v1alpha
    kind: GpuClaimParameters
    name: gpu-params2
---
apiVersion: v1
kind: Pod
metadata:
  name: test-shared-claim0
spec:
  restartPolicy: Never
  containers:
  - name: with-resource
    image: registry.k8s.io/e2e-test-images/busybox:1.29-2
    command: ["sh", "-c", "set && ls -la /dev/dri/ && sleep 30"]
    resources:
      claims:
      - name: resource
  - name: without-resource
    image: registry.k8s.io/e2e-test-images/busybox:1.29-2
    command: ["sh", "-c", "set && ls -la /dev/ && sleep 30"]
  resourceClaims:
  - name: resource
    source:
      resourceClaimName: gpu-claim2
---
apiVersion: v1
kind: Pod
metadata:
  name: test-shared-claim1
spec:
  restartPolicy: Never
  containers:
  - name: with-resource
    image: registry.k8s.io/e2e-test-images/busybox:1.29-2
    command: ["sh", "-c", "set && ls -la /dev/dri/ && sleep 30"]
    resources:
      claims:
      - name: resource
  - name: without-resource
    image: registry.k8s.io/e2e-test-images/busybox:1.29-2
    command: ["sh", "-c", "set && ls -la /dev/ && sleep 30"]
  resourceClaims:
  - name: resource
    source:
      resourceClaimName: gpu-claim2
