@startuml
title "Delayed allocation"

actor       Actor
participant ResourceClaim
participant Pod
participant Controller
participant Plugin

Actor -> ResourceClaim : deploy 
ResourceClaim -> Controller : notify
note right of Controller
  the difference is here
end note
Controller -> Controller : wait for first user
Actor -> Pod : deploy
Pod -> Controller : find suitable nodes
Pod -> Controller : Allocate on Node N
Plugin -> ResourceClaim : prepare resource and mark Ready

@enduml

