/*
 * Copyright (c) 2024, Intel Corporation.  All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/intel/intel-resource-drivers-for-kubernetes/pkg/intel.com/resource/gaudi/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGaudiClaimParameters implements GaudiClaimParametersInterface
type FakeGaudiClaimParameters struct {
	Fake *FakeGaudiV1alpha1
	ns   string
}

var gaudiclaimparametersResource = v1alpha1.SchemeGroupVersion.WithResource("gaudiclaimparameters")

var gaudiclaimparametersKind = v1alpha1.SchemeGroupVersion.WithKind("GaudiClaimParameters")

// Get takes name of the gaudiClaimParameters, and returns the corresponding gaudiClaimParameters object, and an error if there is any.
func (c *FakeGaudiClaimParameters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GaudiClaimParameters, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(gaudiclaimparametersResource, c.ns, name), &v1alpha1.GaudiClaimParameters{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GaudiClaimParameters), err
}

// List takes label and field selectors, and returns the list of GaudiClaimParameters that match those selectors.
func (c *FakeGaudiClaimParameters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GaudiClaimParametersList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(gaudiclaimparametersResource, gaudiclaimparametersKind, c.ns, opts), &v1alpha1.GaudiClaimParametersList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GaudiClaimParametersList{ListMeta: obj.(*v1alpha1.GaudiClaimParametersList).ListMeta}
	for _, item := range obj.(*v1alpha1.GaudiClaimParametersList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested gaudiClaimParameters.
func (c *FakeGaudiClaimParameters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(gaudiclaimparametersResource, c.ns, opts))

}

// Create takes the representation of a gaudiClaimParameters and creates it.  Returns the server's representation of the gaudiClaimParameters, and an error, if there is any.
func (c *FakeGaudiClaimParameters) Create(ctx context.Context, gaudiClaimParameters *v1alpha1.GaudiClaimParameters, opts v1.CreateOptions) (result *v1alpha1.GaudiClaimParameters, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(gaudiclaimparametersResource, c.ns, gaudiClaimParameters), &v1alpha1.GaudiClaimParameters{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GaudiClaimParameters), err
}

// Update takes the representation of a gaudiClaimParameters and updates it. Returns the server's representation of the gaudiClaimParameters, and an error, if there is any.
func (c *FakeGaudiClaimParameters) Update(ctx context.Context, gaudiClaimParameters *v1alpha1.GaudiClaimParameters, opts v1.UpdateOptions) (result *v1alpha1.GaudiClaimParameters, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(gaudiclaimparametersResource, c.ns, gaudiClaimParameters), &v1alpha1.GaudiClaimParameters{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GaudiClaimParameters), err
}

// Delete takes name of the gaudiClaimParameters and deletes it. Returns an error if one occurs.
func (c *FakeGaudiClaimParameters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(gaudiclaimparametersResource, c.ns, name, opts), &v1alpha1.GaudiClaimParameters{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGaudiClaimParameters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(gaudiclaimparametersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.GaudiClaimParametersList{})
	return err
}

// Patch applies the patch and returns the patched gaudiClaimParameters.
func (c *FakeGaudiClaimParameters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GaudiClaimParameters, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(gaudiclaimparametersResource, c.ns, name, pt, data, subresources...), &v1alpha1.GaudiClaimParameters{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GaudiClaimParameters), err
}
