/*
 * Copyright (c) 2024, Intel Corporation.  All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/intel/intel-resource-drivers-for-kubernetes/pkg/intel.com/resource/gaudi/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGaudiAllocationStates implements GaudiAllocationStateInterface
type FakeGaudiAllocationStates struct {
	Fake *FakeGaudiV1alpha1
	ns   string
}

var gaudiallocationstatesResource = v1alpha1.SchemeGroupVersion.WithResource("gaudiallocationstates")

var gaudiallocationstatesKind = v1alpha1.SchemeGroupVersion.WithKind("GaudiAllocationState")

// Get takes name of the gaudiAllocationState, and returns the corresponding gaudiAllocationState object, and an error if there is any.
func (c *FakeGaudiAllocationStates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GaudiAllocationState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(gaudiallocationstatesResource, c.ns, name), &v1alpha1.GaudiAllocationState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GaudiAllocationState), err
}

// List takes label and field selectors, and returns the list of GaudiAllocationStates that match those selectors.
func (c *FakeGaudiAllocationStates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GaudiAllocationStateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(gaudiallocationstatesResource, gaudiallocationstatesKind, c.ns, opts), &v1alpha1.GaudiAllocationStateList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GaudiAllocationStateList{ListMeta: obj.(*v1alpha1.GaudiAllocationStateList).ListMeta}
	for _, item := range obj.(*v1alpha1.GaudiAllocationStateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested gaudiAllocationStates.
func (c *FakeGaudiAllocationStates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(gaudiallocationstatesResource, c.ns, opts))

}

// Create takes the representation of a gaudiAllocationState and creates it.  Returns the server's representation of the gaudiAllocationState, and an error, if there is any.
func (c *FakeGaudiAllocationStates) Create(ctx context.Context, gaudiAllocationState *v1alpha1.GaudiAllocationState, opts v1.CreateOptions) (result *v1alpha1.GaudiAllocationState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(gaudiallocationstatesResource, c.ns, gaudiAllocationState), &v1alpha1.GaudiAllocationState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GaudiAllocationState), err
}

// Update takes the representation of a gaudiAllocationState and updates it. Returns the server's representation of the gaudiAllocationState, and an error, if there is any.
func (c *FakeGaudiAllocationStates) Update(ctx context.Context, gaudiAllocationState *v1alpha1.GaudiAllocationState, opts v1.UpdateOptions) (result *v1alpha1.GaudiAllocationState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(gaudiallocationstatesResource, c.ns, gaudiAllocationState), &v1alpha1.GaudiAllocationState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GaudiAllocationState), err
}

// Delete takes name of the gaudiAllocationState and deletes it. Returns an error if one occurs.
func (c *FakeGaudiAllocationStates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(gaudiallocationstatesResource, c.ns, name, opts), &v1alpha1.GaudiAllocationState{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGaudiAllocationStates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(gaudiallocationstatesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.GaudiAllocationStateList{})
	return err
}

// Patch applies the patch and returns the patched gaudiAllocationState.
func (c *FakeGaudiAllocationStates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GaudiAllocationState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(gaudiallocationstatesResource, c.ns, name, pt, data, subresources...), &v1alpha1.GaudiAllocationState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GaudiAllocationState), err
}
