apiVersion: v2
name: intel-qat-resource-driver
description: A Helm chart for a Dynamic Resource Allocation (DRA) Intel QAT Resource Driver

type: application
version: 0.2.0
appVersion: "v0.2.0"
home: https://github.com/intel/intel-resource-drivers-for-kubernetes/charts

dependencies:
  - name: node-feature-discovery
    alias: nfd
    version: "0.17.1"
    condition: nfd.enabled
    repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts

annotations:
  org.opencontainers.image.url: "https://github.com/intel/intel-resource-drivers-for-kubernetes"
  org.opencontainers.image.source: "https://github.com/intel/intel-resource-drivers-for-kubernetes"
  org.opencontainers.image.version: "0.2.0"
  org.opencontainers.image.title: "Intel QAT Resource Driver"
  org.opencontainers.image.description: "This chart installs the Intel QAT resource driver on Kubernetes."
