apiVersion: resource.k8s.io/v1beta1
kind: ResourceClaimTemplate
metadata:
  name: qat-template-sym
spec:
  spec:
    devices:
      requests:
      - name: qat-request-sym
        deviceClassName: qat.intel.com
        selectors:
        - cel:
           expression: |-
              device.attributes["qat.intel.com"].services == "sym" ||
              device.attributes["qat.intel.com"].services == "sym;asym" ||
              device.attributes["qat.intel.com"].services == "sym;dc" ||
              device.attributes["qat.intel.com"].services == "asym;sym" ||
              device.attributes["qat.intel.com"].services == "dc;sym" ||

---
apiVersion: resource.k8s.io/v1beta1
kind: ResourceClaimTemplate
metadata:
  name: qat-template-asym
spec:
  spec:
    devices:
      requests:
      - name: qat-request-asym
        deviceClassName: qat.intel.com
        selectors:
        - cel:
           expression: |-
              device.attributes["qat.intel.com"].services == "asym" ||
              device.attributes["qat.intel.com"].services == "asym;sym" ||
              device.attributes["qat.intel.com"].services == "asym;dc" ||
              device.attributes["qat.intel.com"].services == "sym;asym" ||
              device.attributes["qat.intel.com"].services == "dc;asym" ||

---
apiVersion: resource.k8s.io/v1beta1
kind: ResourceClaimTemplate
metadata:
  name: qat-template-dc
spec:
  spec:
    devices:
      requests:
      - name: qat-request-dc
        deviceClassName: qat.intel.com
        selectors:
        - cel:
           expression: |-
              device.attributes["qat.intel.com"].services == "dc" ||
              device.attributes["qat.intel.com"].services == "dc;sym" ||
              device.attributes["qat.intel.com"].services == "dc;asym" ||
              device.attributes["qat.intel.com"].services == "sym;dc" ||
              device.attributes["qat.intel.com"].services == "asym;dc" ||
              device.attributes["qat.intel.com"].services == "dcc"

---
apiVersion: v1
kind: Deployment
metadata:
  name: qat-sample-sym
  labels:
    app: inline-qat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inline-qat-deployment
  template:
    metadata:
      labels:
        app: inline-qat-deployment
    spec:
      containers:
      - name: with-resource
        image: registry.k8s.io/e2e-test-images/busybox:1.29-2
        command: ["sh", "-c", "ls -la /dev/vfio/ && sleep 300"]
        securityContext:
          capabilities:
            add:
              ["IPC_LOCK"]
        resources:
          claims:
          - name: resource-sym
          - name: resource-asym
          - name: resource-dc
      - name: without-resource
        image: registry.k8s.io/e2e-test-images/busybox:1.29-2
        command: ["sh", "-c", "ls -la /dev/ && sleep 300"]
      resourceClaims:
      - name: resource-sym
        resourceClaimTemplateName: qat-template-sym
      - name: resource-asym
        resourceClaimTemplateName: qat-template-asym
      - name: resource-dc
        resourceClaimTemplateName: qat-template-dc
