#
# Copyright (C) 2022-2026 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

ARG LOCAL_LICENSES

FROM golang:1.26.7@sha256:dc2521c2a906db43073b8b4d99f491b6341cf15610b6ebbab187c45153f9959e AS build
WORKDIR /build
COPY . .

# Build GPU DRA driver
RUN make gpu && \
mkdir -p /install_root && \
if [ -z "$LOCAL_LICENSES" ]; then \
    make licenses; \
fi && \
cp -r licenses /install_root/ && \
cp bin/kubelet-gpu-plugin /install_root/

FROM scratch
WORKDIR /
LABEL description="Intel GPU resource driver for Kubernetes"
LABEL org.opencontainers.image.source="https://github.com/intel/intel-resource-drivers-for-kubernetes"
LABEL org.opencontainers.image.description="Intel GPU resource driver for Kubernetes"

COPY --from=build /install_root /
CMD ["/kubelet-gpu-plugin"]
