# Copyright (c) 2025, Intel Corporation.  All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# 1. Build fake libhlml for Gaudi tests
FROM golang:1.25.4@sha256:698183780de28062f4ef46f82a79ec0ae69d2d22f7b160cf69f71ea8d98bf25d AS build
WORKDIR /build
COPY . .

RUN cd hack/fake_libhlml && \
make clean && make

FROM ubuntu:24.04@sha256:80dd3c3b9c6cecb9f1667e9290b3bc61b78c2678c02cbdae5f0fea92cc6734ab AS ubuntu
ARG UID=1000
ARG GID=1000
# add fake hlml shared library for Gaudi tests
COPY --from=build /build/hack/fake_libhlml/fake_libhlml.so /usr/lib/habanalabs/libhlml.so
COPY --from=build --chown=${UID}:${GID} /usr/local/go /home/ubuntu/go

# add xpu-smi shared library for GPU tests and other dependencies
RUN \
apt-get update && \
apt-get install -y make gcc wget software-properties-common python3-launchpadlib git yamllint shellcheck bc && \
add-apt-repository -y ppa:kobuk-team/intel-graphics && \
apt-get update && \
apt-get install -y libze-intel-gpu1 libze1 intel-metrics-discovery intel-opencl-icd clinfo intel-gsc && \
wget -qO /tmp/xpu-smi.deb https://github.com/intel/xpumanager/releases/download/V1.3.1/xpu-smi_1.3.1_20250724.061629.60921e5e_u24.04_amd64.deb && \
apt-get install -y /tmp/xpu-smi.deb && \
rm /tmp/xpu-smi.deb && \
echo 'export PATH=/home/ubuntu/go/bin:$PATH' >> /home/ubuntu/.bashrc && \
wget -q https://github.com/golangci/golangci-lint/releases/download/v2.7.2/golangci-lint-2.7.2-linux-amd64.tar.gz && \
tar zxf golangci-lint-2.7.2-linux-amd64.tar.gz --strip-components=1 golangci-lint-2.7.2-linux-amd64/golangci-lint && \
mv golangci-lint /usr/local/bin/golangci-lint && \
rm golangci-lint-2.7.2-linux-amd64.tar.gz && \
unset http_proxy https_proxy no_proxy

RUN \
mkdir /github && \
chmod 777 /github && \
mkdir /home/ubuntu/src && \
chown -R ${UID}:${GID} /home/ubuntu

ENV GOLANGCI_LINT_CACHE=/home/ubuntu/.lint-cache
ENV GOROOT=/home/ubuntu/go
ENV GOCACHE=/home/ubuntu/.cache/go-build
ENV GOMODCACHE=/home/ubuntu/.cache/go-mod
ENV PATH=/home/ubuntu/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

USER ubuntu
WORKDIR /home/ubuntu
