# Copyright (c) 2025, Intel Corporation.  All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# 1. Build fake libhlml for Gaudi tests
FROM golang:1.25.8@sha256:dfae680962532eeea67ab297f1166c2c4e686edb9a8f05f9d02d96fc9191833e AS build
WORKDIR /build
COPY . .

RUN \
wget -c https://vault.habana.ai/artifactory/debian/noble/pool/main/h/habanalabs-firmware-tools/habanalabs-firmware-tools_1.23.0-695_amd64.deb && \
apt-get update && \
apt-get install -y --ignore-missing ./habanalabs-firmware-tools_1.23.0-695_amd64.deb && \
cd hack/fake_libhlml && \
make clean && make

FROM ubuntu:24.04@sha256:80dd3c3b9c6cecb9f1667e9290b3bc61b78c2678c02cbdae5f0fea92cc6734ab AS ubuntu
ARG UID=1000
ARG GID=1000
# add fake hlml shared library for Gaudi tests
COPY --from=build /build/hack/fake_libhlml/fake_libhlml.so /usr/lib/habanalabs/libhlml.so
COPY --from=build /usr/include/habanalabs/hlml.h /usr/include/habanalabs/hlml.h
COPY --from=build --chown=${UID}:${GID} /usr/local/go /home/ubuntu/go

RUN \
apt-get update && \
apt-get install -y make git bc gcc && \
echo "export PATH=/home/ubuntu/go/bin:$PATH" >> /home/ubuntu/.bashrc

RUN \
mkdir /github && \
chmod 777 /github && \
mkdir /home/ubuntu/src && \
chown -R ${UID}:${GID} /home/ubuntu

ENV GOLANGCI_LINT_CACHE=/home/ubuntu/.lint-cache
ENV GOROOT=/home/ubuntu/go
ENV GOCACHE=/home/ubuntu/.cache/go-build
ENV GOMODCACHE=/home/ubuntu/.cache/go-mod
ENV PATH=/home/ubuntu/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

USER ubuntu
WORKDIR /home/ubuntu
