FROM golang:1.24.2@sha256:b51b7beeabe2e2d8438ba4295c59d584049873a480ba0e7b56d80db74b3e3a3a as build
ARG LOCAL_LICENSES
WORKDIR /build
COPY . .

RUN make bin/device-faker && \
mkdir -p /install_root && \
if [ -z "$LOCAL_LICENSES" ]; then \
    make licenses; \
fi && \
cp -r licenses /install_root/ && \
cp bin/device-faker /install_root/


FROM alpine AS template
COPY --from=build /install_root/device-faker /device-faker


RUN mkdir -p /opt/templates && \
    /device-faker gpu -n && \
    mv /tmp/gpu-template-*.json /opt/templates/gpu-template.json && \
    /device-faker gaudi -n && \
    mv /tmp/gaudi-template-*.json /opt/templates/gaudi-template.json && \
    chmod 644 /opt/templates/*.json

FROM scratch
LABEL description="Intel Device Faker"
COPY --from=build /install_root/device-faker /device-faker
COPY --from=template /opt/templates /opt/templates
ENTRYPOINT ["/device-faker"]
