#
# Copyright (C) 2022-2026 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

ARG LOCAL_LICENSES

FROM golang:1.26.3@sha256:6b3de2e6b4ccfc5fae404042cb1a025b1de13c73458e50455e3143bf12e98eae AS build
WORKDIR /build
COPY . .

# Build GPU DRA driver
RUN make gpu && \
mkdir -p /install_root && \
if [ -z "$LOCAL_LICENSES" ]; then \
    make licenses; \
fi && \
cp -r licenses /install_root/ && \
cp bin/kubelet-gpu-plugin /install_root/

FROM scratch
WORKDIR /
LABEL description="Intel GPU resource driver for Kubernetes"
LABEL org.opencontainers.image.source="https://github.com/intel/intel-resource-drivers-for-kubernetes"
LABEL org.opencontainers.image.description="Intel GPU resource driver for Kubernetes"

COPY --from=build /install_root /
CMD ["/kubelet-gpu-plugin"]
