FROM golang:1.25.8@sha256:dfae680962532eeea67ab297f1166c2c4e686edb9a8f05f9d02d96fc9191833e AS build
ARG LOCAL_LICENSES
WORKDIR /build
COPY . .

RUN make bin/device-faker && \
mkdir -p /install_root && \
if [ -z "$LOCAL_LICENSES" ]; then \
    make licenses; \
fi && \
cp -r licenses /install_root/ && \
cp bin/device-faker /install_root/


FROM alpine AS template
COPY --from=build /install_root/device-faker /device-faker


RUN mkdir -p /opt/templates && \
    /device-faker gpu -n && \
    mv /tmp/gpu-template-*.json /opt/templates/gpu-template.json && \
    /device-faker gaudi -n && \
    mv /tmp/gaudi-template-*.json /opt/templates/gaudi-template.json && \
    chmod 644 /opt/templates/*.json

FROM scratch
LABEL description="Intel Device Faker"
COPY --from=build /install_root/device-faker /device-faker
COPY --from=template /opt/templates /opt/templates
ENTRYPOINT ["/device-faker"]
