#
# Copyright (C) 2022-2026 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

FROM golang:1.26.3@sha256:6b3de2e6b4ccfc5fae404042cb1a025b1de13c73458e50455e3143bf12e98eae AS build
ARG LOCAL_LICENSES
WORKDIR /build
COPY . .

RUN make qat && \
mkdir -p /install_root && \
if [ -z "$LOCAL_LICENSES" ]; then \
    make licenses; \
fi && \
cp -r licenses /install_root/ && \
cp bin/kubelet-qat-plugin /install_root/ && \
cp bin/qat-showdevice /install_root/


FROM scratch
WORKDIR /
LABEL description="Intel QAT resource driver for Kubernetes"

COPY --from=build /install_root /
