FROM golang:1.23.4@sha256:70031844b8c225351d0bb63e2c383f80db85d92ba894e3da7e13bcf80efa9a37 as build
ARG LOCAL_LICENSES
WORKDIR /build
COPY . .

RUN make bin/device-faker && \
mkdir -p /install_root && \
if [ -z "$LOCAL_LICENSES" ]; then \
    make licenses; \
fi && \
cp -r licenses /install_root/ && \
cp bin/device-faker /install_root/


FROM alpine AS template
COPY --from=build /install_root/device-faker /device-faker


RUN mkdir -p /opt/templates && \
    /device-faker gpu -n && \
    mv /tmp/gpu-template-*.json /opt/templates/gpu-template.json && \
    /device-faker gaudi -n && \
    mv /tmp/gaudi-template-*.json /opt/templates/gaudi-template.json && \
    chmod 644 /opt/templates/*.json

FROM scratch
LABEL description="Intel Device Faker"
COPY --from=build /install_root/device-faker /device-faker
COPY --from=template /opt/templates /opt/templates
ENTRYPOINT ["/device-faker"]
