# Copyright 2017 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARCH=amd64
PKG = github.com/intel/intel-resource-drivers-for-kubernetes
GO111MODULE = on
GOPATH ?= $(shell go env GOPATH)
GOBIN ?= $(GOPATH)/bin
export GOPATH GOBIN GO111MODULE

GIT_COMMIT = $(shell git rev-parse HEAD)
BUILD_DATE = $(shell date -u +"%Y-%m-%dT%H:%M:%SZ")
GIT_BRANCH ?= $(shell git branch --show-current)
VERSION ?= v0.2.0

EXT_LDFLAGS = -static
LDFLAGS = \
 -s -w -extldflags $(EXT_LDFLAGS) \
 -X ${PKG}/pkg/version.driverVersion=${IMAGE_VERSION} \
 -X ${PKG}/pkg/version.gitCommit=${GIT_COMMIT} \
 -X ${PKG}/pkg/version.buildDate=${BUILD_DATE}

GOLICENSES_VERSION?=v1.6.0
ifneq ("$(wildcard licenses/)","")
LOCAL_LICENSES=TRUE
endif

MODULE = github.com/intel/intel-resource-drivers-for-kubernetes

# Use a custom version for E2E tests if we are testing in CI
REGISTRY ?= registry.local
IMAGENAME ?= intel-gpu-resource-driver
IMAGE_VERSION ?= $(VERSION)
IMAGE_TAG ?= $(REGISTRY)/$(IMAGENAME):$(IMAGE_VERSION)

ifndef DOCKER
	PODMAN_VERSION := $(shell command podman version 2>/dev/null)
	DOCKER_VERSION := $(shell command docker version 2>/dev/null)
    ifdef DOCKER_VERSION
        DOCKER := docker
	else ifdef PODMAN_VERSION
		DOCKER := podman
	endif
endif

.EXPORT_ALL_VARIABLES:

GPU_BINARIES = bin/gpu-controller bin/gpu-kubelet-plugin bin/gpu-gas-status-updater
COMMON_SRC = \
 Makefile \
 pkg/version/version.go \
 pkg/intel.com/resource/gpu/clientset/versioned/*.go \
 pkg/intel.com/resource/gpu/v1alpha2/api/*.go \
 pkg/intel.com/resource/gpu/v1alpha2/*.go \
 pkg/sriov/*.go \
 go.sum

.PHONY: build
build: $(GPU_BINARIES)

bin/gpu-kubelet-plugin: cmd/gpu-kubelet-plugin/*.go $(COMMON_SRC)
	CGO_ENABLED=0 GOOS=linux GOARCH=${ARCH} \
	  go build -a -ldflags "${LDFLAGS}" -mod vendor -o $@ ./cmd/gpu-kubelet-plugin

bin/gpu-controller: cmd/gpu-controller/*.go $(COMMON_SRC)
	CGO_ENABLED=0 GOOS=linux GOARCH=${ARCH} \
	  go build -a -ldflags "${LDFLAGS}" -mod vendor -o $@ ./cmd/gpu-controller

.PHONY: bin/gas-status-updater
bin/gpu-gas-status-updater: cmd/gpu-gas-status-updater/*.go $(COMMON_SRC)
	CGO_ENABLED=0 GOOS=linux GOARCH=${ARCH} \
	  go build -a -ldflags "${LDFLAGS}" -mod vendor -o $@ ./cmd/gpu-gas-status-updater

.PHONY: branch-build
# test that all commits in $GIT_BRANCH (default=current) build
branch-build:
	current=$$(git branch --show-current); echo "Current branch: $$current"; \
	for commit in $$(git log --reverse --pretty=oneline origin/master...$(GIT_BRANCH) | cut -d' ' -f1); do \
		echo "Building: '$$commit'..."; git checkout $$commit && make build; done; \
	git checkout $$current

.PHONY: container-build
container-build: update-vendor
	$(DOCKER) build --pull --platform="linux/$(ARCH)" -t $(IMAGE_TAG) \
	--build-arg LOCAL_LICENSES=$(LOCAL_LICENSES) ./

.PHONY: container-local
container-local: container-build
	$(DOCKER) save -o /tmp/temp_image.tar $(IMAGE_TAG)
	sudo ctr -n k8s.io image import /tmp/temp_image.tar
	rm /tmp/temp_image.tar

.PHONY: container-push
container-push: container-build
	$(DOCKER) push $(IMAGE_TAG)

.PHONY: clean cleanall
clean:
	rm -rf $(BINARIES)
cleanall: clean
	rm -rf vendor/* bin/*

.PHONY: rm-clientset
rm-clientset:
	rm -rf "$(CURDIR)/pkg/intel.com/resource/gpu/clientset/"

.PHONY: generate
generate: generate-crds

.PHONY: generate-crds
generate-crds: generate-deepcopy
	controller-gen \
		crd:crdVersions=v1 \
		paths=$(CURDIR)/pkg/intel.com/resource/gpu/v1alpha2/ \
		output:crd:dir=$(CURDIR)/deployments/static/crds

.PHONY: generate-deepcopy
generate-deepcopy: generate-clientset
	controller-gen \
		object:headerFile=$(CURDIR)/hack/boilerplate.go.txt,year=$(shell date +"%Y") \
		paths=$(CURDIR)/pkg/intel.com/resource/gpu/v1alpha2/ \
		output:object:dir=$(CURDIR)/pkg/intel.com/resource/gpu/v1alpha2

.PHONY: generate-clientset
generate-clientset: rm-clientset
	client-gen \
		--go-header-file=$(CURDIR)/hack/boilerplate.go.txt \
		--clientset-name "versioned" \
		--build-tag "ignore_autogenerated" \
		--output-package "$(MODULE)/pkg/intel.com/resource/gpu/clientset" \
		--input-base "$(MODULE)/pkg/intel.com/resource" \
		--output-base "$(CURDIR)/pkg/tmp_clientset" \
		--input "gpu/v1alpha2" \
		--plural-exceptions "GpuClassParameters:GpuClassParameters,GpuClaimParameters:GpuClaimParameters"
	mkdir -p $(CURDIR)/pkg/intel.com/resource/
	mv $(CURDIR)/pkg/tmp_clientset/$(MODULE)/pkg/intel.com/resource/gpu/clientset \
		$(CURDIR)/pkg/intel.com/resource/gpu/
	rm -rf $(CURDIR)/pkg/tmp_clientset

.PHONY: update-vendor
update-vendor:
	go mod tidy
	go mod vendor

.PHONY: clean-licenses
clean-licenses:
	rm -rf licenses

.PHONY: licenses
licenses: clean-licenses
	GO111MODULE=on go run github.com/google/go-licenses@$(GOLICENSES_VERSION) \
	save "./cmd/controller" "./cmd/kubelet-plugin" "./pkg/version/" "./pkg/intel.com/resource/gpu/v1alpha2" \
	"./pkg/intel.com/resource/gpu/v1alpha2/api" "./pkg/intel.com/resource/gpu/clientset/versioned/" --save_path licenses


# linting targets for Go and other code
.PHONY: lint format cilint vet shellcheck yamllint

lint: format cilint vet build shellcheck yamllint

format:
	gofmt -w -s -l ./

cilint:
	golangci-lint --max-same-issues 0 --max-issues-per-linter 0 run ./...

vet:
	go vet  $(PKG)/...

# exclude env.sh + SC1091, shellcheck external file handling is broken
shellcheck:
	find . -name '*.sh' | grep -v -e vendor/ -e /env.sh |\
	xargs shellcheck -e SC1091

yamllint:
	yamllint -d relaxed --no-warnings *.yaml deployments/ hack/

.PHONY: test coverage
COVERAGE_FILE := coverage.out
test: build
	go test -v -coverprofile=$(COVERAGE_FILE) $(MODULE)/...

coverage: test
	go tool cover -func=$(COVERAGE_FILE)
