/*
 * Copyright (c) 2022, Intel Corporation.  All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha

import (
	v1alpha "github.com/intel/intel-resource-drivers-for-kubernetes/pkg/crd/intel/v1alpha"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// DeviceClassParametersLister helps list DeviceClassParameters.
// All objects returned here must be treated as read-only.
type DeviceClassParametersLister interface {
	// List lists all DeviceClassParameters in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha.DeviceClassParameters, err error)
	// Get retrieves the DeviceClassParameters from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha.DeviceClassParameters, error)
	DeviceClassParametersListerExpansion
}

// deviceClassParametersLister implements the DeviceClassParametersLister interface.
type deviceClassParametersLister struct {
	indexer cache.Indexer
}

// NewDeviceClassParametersLister returns a new DeviceClassParametersLister.
func NewDeviceClassParametersLister(indexer cache.Indexer) DeviceClassParametersLister {
	return &deviceClassParametersLister{indexer: indexer}
}

// List lists all DeviceClassParameters in the indexer.
func (s *deviceClassParametersLister) List(selector labels.Selector) (ret []*v1alpha.DeviceClassParameters, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha.DeviceClassParameters))
	})
	return ret, err
}

// Get retrieves the DeviceClassParameters from the index for a given name.
func (s *deviceClassParametersLister) Get(name string) (*v1alpha.DeviceClassParameters, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha.Resource("deviceclassparameters"), name)
	}
	return obj.(*v1alpha.DeviceClassParameters), nil
}
