/*
 * Copyright (c) 2022, Intel Corporation.  All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha

import (
	v1alpha "github.com/intel/intel-resource-drivers-for-kubernetes/pkg/crd/intel/v1alpha"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// GpuAllocationStateLister helps list GpuAllocationStates.
// All objects returned here must be treated as read-only.
type GpuAllocationStateLister interface {
	// List lists all GpuAllocationStates in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha.GpuAllocationState, err error)
	// GpuAllocationStates returns an object that can list and get GpuAllocationStates.
	GpuAllocationStates(namespace string) GpuAllocationStateNamespaceLister
	GpuAllocationStateListerExpansion
}

// gpuAllocationStateLister implements the GpuAllocationStateLister interface.
type gpuAllocationStateLister struct {
	indexer cache.Indexer
}

// NewGpuAllocationStateLister returns a new GpuAllocationStateLister.
func NewGpuAllocationStateLister(indexer cache.Indexer) GpuAllocationStateLister {
	return &gpuAllocationStateLister{indexer: indexer}
}

// List lists all GpuAllocationStates in the indexer.
func (s *gpuAllocationStateLister) List(selector labels.Selector) (ret []*v1alpha.GpuAllocationState, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha.GpuAllocationState))
	})
	return ret, err
}

// GpuAllocationStates returns an object that can list and get GpuAllocationStates.
func (s *gpuAllocationStateLister) GpuAllocationStates(namespace string) GpuAllocationStateNamespaceLister {
	return gpuAllocationStateNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// GpuAllocationStateNamespaceLister helps list and get GpuAllocationStates.
// All objects returned here must be treated as read-only.
type GpuAllocationStateNamespaceLister interface {
	// List lists all GpuAllocationStates in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha.GpuAllocationState, err error)
	// Get retrieves the GpuAllocationState from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha.GpuAllocationState, error)
	GpuAllocationStateNamespaceListerExpansion
}

// gpuAllocationStateNamespaceLister implements the GpuAllocationStateNamespaceLister
// interface.
type gpuAllocationStateNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all GpuAllocationStates in the indexer for a given namespace.
func (s gpuAllocationStateNamespaceLister) List(selector labels.Selector) (ret []*v1alpha.GpuAllocationState, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha.GpuAllocationState))
	})
	return ret, err
}

// Get retrieves the GpuAllocationState from the indexer for a given namespace and name.
func (s gpuAllocationStateNamespaceLister) Get(name string) (*v1alpha.GpuAllocationState, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha.Resource("gpuallocationstate"), name)
	}
	return obj.(*v1alpha.GpuAllocationState), nil
}
