/*
 * Copyright (c) 2023, Intel Corporation.  All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha

import (
	v1alpha "github.com/intel/intel-resource-drivers-for-kubernetes/pkg/crd/intel/v1alpha"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// GpuClaimParametersLister helps list GpuClaimParameters.
// All objects returned here must be treated as read-only.
type GpuClaimParametersLister interface {
	// List lists all GpuClaimParameters in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha.GpuClaimParameters, err error)
	// GpuClaimParameters returns an object that can list and get GpuClaimParameters.
	GpuClaimParameters(namespace string) GpuClaimParametersNamespaceLister
	GpuClaimParametersListerExpansion
}

// gpuClaimParametersLister implements the GpuClaimParametersLister interface.
type gpuClaimParametersLister struct {
	indexer cache.Indexer
}

// NewGpuClaimParametersLister returns a new GpuClaimParametersLister.
func NewGpuClaimParametersLister(indexer cache.Indexer) GpuClaimParametersLister {
	return &gpuClaimParametersLister{indexer: indexer}
}

// List lists all GpuClaimParameters in the indexer.
func (s *gpuClaimParametersLister) List(selector labels.Selector) (ret []*v1alpha.GpuClaimParameters, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha.GpuClaimParameters))
	})
	return ret, err
}

// GpuClaimParameters returns an object that can list and get GpuClaimParameters.
func (s *gpuClaimParametersLister) GpuClaimParameters(namespace string) GpuClaimParametersNamespaceLister {
	return gpuClaimParametersNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// GpuClaimParametersNamespaceLister helps list and get GpuClaimParameters.
// All objects returned here must be treated as read-only.
type GpuClaimParametersNamespaceLister interface {
	// List lists all GpuClaimParameters in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha.GpuClaimParameters, err error)
	// Get retrieves the GpuClaimParameters from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha.GpuClaimParameters, error)
	GpuClaimParametersNamespaceListerExpansion
}

// gpuClaimParametersNamespaceLister implements the GpuClaimParametersNamespaceLister
// interface.
type gpuClaimParametersNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all GpuClaimParameters in the indexer for a given namespace.
func (s gpuClaimParametersNamespaceLister) List(selector labels.Selector) (ret []*v1alpha.GpuClaimParameters, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha.GpuClaimParameters))
	})
	return ret, err
}

// Get retrieves the GpuClaimParameters from the indexer for a given namespace and name.
func (s gpuClaimParametersNamespaceLister) Get(name string) (*v1alpha.GpuClaimParameters, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha.Resource("gpuclaimparameters"), name)
	}
	return obj.(*v1alpha.GpuClaimParameters), nil
}
