/*
 * Copyright (c) 2023, Intel Corporation.  All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha

import (
	"context"
	"time"

	scheme "github.com/intel/intel-resource-drivers-for-kubernetes/pkg/crd/intel/clientset/versioned/scheme"
	v1alpha "github.com/intel/intel-resource-drivers-for-kubernetes/pkg/crd/intel/v1alpha"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GpuAllocationStatesGetter has a method to return a GpuAllocationStateInterface.
// A group's client should implement this interface.
type GpuAllocationStatesGetter interface {
	GpuAllocationStates(namespace string) GpuAllocationStateInterface
}

// GpuAllocationStateInterface has methods to work with GpuAllocationState resources.
type GpuAllocationStateInterface interface {
	Create(ctx context.Context, gpuAllocationState *v1alpha.GpuAllocationState, opts v1.CreateOptions) (*v1alpha.GpuAllocationState, error)
	Update(ctx context.Context, gpuAllocationState *v1alpha.GpuAllocationState, opts v1.UpdateOptions) (*v1alpha.GpuAllocationState, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha.GpuAllocationState, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha.GpuAllocationStateList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha.GpuAllocationState, err error)
	GpuAllocationStateExpansion
}

// gpuAllocationStates implements GpuAllocationStateInterface
type gpuAllocationStates struct {
	client rest.Interface
	ns     string
}

// newGpuAllocationStates returns a GpuAllocationStates
func newGpuAllocationStates(c *GpuV1alphaClient, namespace string) *gpuAllocationStates {
	return &gpuAllocationStates{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the gpuAllocationState, and returns the corresponding gpuAllocationState object, and an error if there is any.
func (c *gpuAllocationStates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha.GpuAllocationState, err error) {
	result = &v1alpha.GpuAllocationState{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("gpuallocationstates").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GpuAllocationStates that match those selectors.
func (c *gpuAllocationStates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha.GpuAllocationStateList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha.GpuAllocationStateList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("gpuallocationstates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested gpuAllocationStates.
func (c *gpuAllocationStates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("gpuallocationstates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a gpuAllocationState and creates it.  Returns the server's representation of the gpuAllocationState, and an error, if there is any.
func (c *gpuAllocationStates) Create(ctx context.Context, gpuAllocationState *v1alpha.GpuAllocationState, opts v1.CreateOptions) (result *v1alpha.GpuAllocationState, err error) {
	result = &v1alpha.GpuAllocationState{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("gpuallocationstates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(gpuAllocationState).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a gpuAllocationState and updates it. Returns the server's representation of the gpuAllocationState, and an error, if there is any.
func (c *gpuAllocationStates) Update(ctx context.Context, gpuAllocationState *v1alpha.GpuAllocationState, opts v1.UpdateOptions) (result *v1alpha.GpuAllocationState, err error) {
	result = &v1alpha.GpuAllocationState{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("gpuallocationstates").
		Name(gpuAllocationState.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(gpuAllocationState).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the gpuAllocationState and deletes it. Returns an error if one occurs.
func (c *gpuAllocationStates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("gpuallocationstates").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *gpuAllocationStates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("gpuallocationstates").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched gpuAllocationState.
func (c *gpuAllocationStates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha.GpuAllocationState, err error) {
	result = &v1alpha.GpuAllocationState{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("gpuallocationstates").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
