apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterRole.yaml
  - clusterRoleBinding.yaml
  - ../../base
  - securityContextConstraints.yaml

# Uncomment if manage-binding=false is needed.
#components:
#  - ../../components/manage-binding-disabled
