apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Uncomment if manage-binding=false is needed.
#components:
#  - ../../components/manage-binding-disabled

patches:
  - path: add-health-monitoring-args.yaml
    target:
      kind: DaemonSet
      name: intel-gpu-resource-driver-kubelet-plugin
