apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: add-health-monitoring-args.yaml
    target:
      kind: DaemonSet
      name: intel-gpu-resource-driver-kubelet-plugin
