kind: ConfigMap
apiVersion: v1
metadata:
  name: defaults
  namespace: intel-gpu-resource-driver
data:
# It is possible to override driver hardcoded defaults:
# - resourceClaimParameters:
#     if resource claim did not include any parameters, these will be used
# - vf-memory
#     per product amount of local memory, in MiB, the auto-added VFs will get
  resourceClaimParameters.config: |
    count=1
    type=gpu
    shareable=true
  vf-memory.config: |
    {
      "max1550": 16385,
      "max1450": 16384,
      "max1100": 8192,
      "flex140": 2048,
      "flex170": 4096,
    }
