apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "intel-gaudi-resource-driver.clusterRoleBindingName" . }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "intel-gaudi-resource-driver.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "intel-gaudi-resource-driver.clusterRoleName" . }}
  apiGroup: rbac.authorization.k8s.io
