{{- if .Values.nfd.enabled }}
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: intel-gaudi-device-rule
spec:
  rules:
    - name: "intel.gaudi"
      labels:
        "intel.feature.node.kubernetes.io/gaudi": "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: {op: In, value: ["1da3"]}
            device: {op: In, value: ["1020", "1030"]}
{{- end }}
