# Default values for intel-gpu-resource-driver.
nameOverride: ""
fullnameOverride: ""
selectorLabelsOverride: {}

# To enable DRA resources allocation as extended resources. K8s v1.33-v1.36 requires FeatureGate.
# See https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/5004-dra-extended-resource .
enableDRAExtendedResources: false
extendedResourceName: intel.com/gpu

imagePullSecrets: []
image:
  repository: ghcr.io/intel/intel-resource-drivers-for-kubernetes
  name: intel-gpu-resource-driver
  pullPolicy: IfNotPresent
  tag: "v0.9.1"

serviceAccount:
  create: true
  annotations: {}
  name: ""
  automount: true

openshift:
  enabled: false
  sccName: intel-gpu-resource-driver

kubeletPlugin:
  healthcheckPort: 51516  # gRPC health check port. Set to -1 to disable.
  podAnnotations: {}
  nodeSelector: {}
    # Label used when nfd.enabled is true.
    # Changes to this are ignored when .Values.nodeFeatureRules.enabled or .Values.nfd.enabled .
    #intel.feature.node.kubernetes.io/gpu: "true"


  # Health monitoring configuration
  healthMonitoring:
    enabled: false
    interval: 5


  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
      # Refer to the official documentation for Node Feature Discovery (NFD)
      # regarding node tainting:
      # https://nfd.sigs.k8s.io/usage/customization-guide#node-tainting
    - key: "node.kubernetes.io/gpu"
      operator: "Exists"
      effect: "NoSchedule"
  affinity: {}

cdi:
  staticPath: /etc/cdi
  dynamicPath: /var/run/cdi

nodeFeatureRules:
  enabled: false

nfd:
  enabled: false # change to true to install NFD to the cluster
  nameOverride: intel-gpu-nfd
  enableNodeFeatureApi: true
