apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "intel-qat-resource-driver.clusterRoleBindingName" . }}
  namespace: {{ include "intel-qat-resource-driver.namespace" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "intel-qat-resource-driver.serviceAccountName" . }}
  namespace: {{ include "intel-qat-resource-driver.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "intel-qat-resource-driver.clusterRoleName" . }}
  apiGroup: rbac.authorization.k8s.io
