apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: intel-qat-device-rule
spec:
  rules:
    - name: "intel.qat"
      labels:
        feature.node.kubernetes.io/qat: "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: {op: In, value: ["8086"]}
            device: {op: In, value: ["4940", "4941", "4944", "4946"]}
            class: {op: In, value: ["0b40"]}
        - feature: kernel.loadedmodule
          matchExpressions:
            intel_qat: {op: Exists}
      matchAny:
        - matchFeatures:
            - feature: kernel.loadedmodule
              matchExpressions:
                vfio_pci: {op: Exists}
        - matchFeatures:
            - feature: kernel.enabledmodule
              matchExpressions:
                vfio-pci: {op: Exists}
