apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-qat-resource-driver-kubelet-plugin
  namespace: {{ include "intel-qat-resource-driver.namespace" . }}
  labels:
    {{- include "intel-qat-resource-driver.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: intel-qat-resource-driver
  template:
    metadata:
      labels:
        app: intel-qat-resource-driver
    spec:
      serviceAccount: intel-qat-resource-driver-service-account
      serviceAccountName: {{ include "intel-qat-resource-driver.serviceAccountName" . }}
      containers:
      - name: kubelet-plugin
        image: {{ include "intel-qat-resource-driver.fullimage" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/kubelet-qat-plugin"]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SYSFS_ROOT
          value: "/sysfs"
        volumeMounts:
        - name: plugins-registry
          mountPath: /var/lib/kubelet/plugins_registry
        - name: plugins
          mountPath: /var/lib/kubelet/plugins
        - name: cdi
          mountPath: /etc/cdi
        - name: varruncdi
          mountPath: /var/run/cdi
        - name: sysfs
          mountPath: /sysfs
        - name: qatconfiguration
          mountPath: /defaults
        securityContext:
          privileged: true
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
      volumes:
      - name: plugins-registry
        hostPath:
          path: /var/lib/kubelet/plugins_registry
      - name: plugins
        hostPath:
          path: /var/lib/kubelet/plugins
      - name: cdi
        hostPath:
          path: /etc/cdi
      - name: varruncdi
        hostPath:
          path: /var/run/cdi
      - name: sysfs
        hostPath:
          path: /sys
      - name: qatconfiguration
        configMap:
          name: intel-qat-resource-driver-configuration
          optional: true
      {{- with .Values.kubeletPlugin.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubeletPlugin.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubeletPlugin.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
