apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: resourceslices-policy-dra-kubelet-plugin-qat
spec:
  policyName: resourceslices-policy-dra-kubelet-plugin-qat
  validationActions: [Deny]
