apiVersion: resource.k8s.io/v1alpha3
kind: ResourceClaimTemplate
metadata:
  name: monitor-claim
spec:
  spec:
    devices:
      requests:
      - name: gaudi
        deviceClassName: gaudi.intel.com
      adminAccess: true
      allocationMode: "All"
---
apiVersion: v1
kind: Pod
metadata:
  name: monitor-pod
spec:
  restartPolicy: Never
  containers:
  - name: monitor
    image: registry.k8s.io/e2e-test-images/busybox:1.29-2
    command: ["sh", "-c", "ls -la /dev/dri/ && sleep 60"]
    resources:
      claims:
      - name: resource
  resourceClaims:
  - name: resource
    resourceClaimTemplateName: monitor-claim
