apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - nfd-intel-gpu-device-rule.yaml
  - nfd-intel-gpu-platform-labeling.yaml

# Uncomment if manage-binding=false is needed.
#components:
#  - ../../components/manage-binding-disabled

patches:
  - path: add-nodeselector-intel-gpu.yaml
