name: Publish devel images

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  packages: write

env:
  repo: ghcr.io/intel/intel-resource-drivers-for-kubernetes

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target:
          - gaudi
          - gpu
          - qat

    steps:
    - name: Check out code
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Install cosign
      uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

    - name: Docker login
      if: ${{ github.event_name == 'push' }}
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Prepare for build
      run: make vendor licenses

    - name: Build and push image
      id: build_and_push
      uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
      with:
        context: ./
        file: ./Dockerfile.${{ matrix.target }}
        push: ${{ github.event_name == 'push' }}
        tags: ${{ env.repo }}/intel-${{ matrix.target }}-resource-driver:devel
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          http_proxy=${{ vars.HTTP_PROXY }}
          https_proxy=${{ vars.HTTPS_PROXY }}
          no_proxy=${{ vars.NO_PROXY }}

    - name: Sign image
      if: ${{ github.event_name == 'push' }}
      env:
        DIGEST: ${{ steps.build_and_push.outputs.digest }}
      run: cosign sign --yes ${{ env.repo }}/intel-${{ matrix.target }}-resource-driver:devel@${{ env.DIGEST }}
